name: musicrights
services:
  musicrights-db:
    image: mariadb:11.3.2
    container_name: musicrights-db
    restart: always
    environment:
      MYSQL_USER: $MARIADB_USER
      MYSQL_PASSWORD: $MUSICRIGHTS_DATABASE_PASSWORD
      MYSQL_DATABASE: $MARIADB_DATABASE
      MYSQL_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
    volumes:
      - musicrights-db-data:/var/lib/mysql
    healthcheck:
      test: [ CMD, healthcheck.sh, --connect, --innodb_initialized ]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - network-musicrights

  musicrights-api:
    build: .
    container_name: musicrights-api
    ports:
      - "80:8085"
    depends_on:
      musicrights-db:
        condition: service_healthy
    environment:
      MUSICRIGHTS_DATABASE_PASSWORD: $MUSICRIGHTS_DATABASE_PASSWORD
      SPRING_PROFILES_ACTIVE: $PROFILE
    networks:
      - network-musicrights

volumes:
  musicrights-db-data:

networks:
  network-musicrights:
    driver: bridge