logginG.level.org.springframework=ERROR
spring.datasource.password=${MUSICRIGHTS_DATABASE_PASSWORD}
spring.datasource.url=jdbc:mariadb://musicrights-db:3306/musicrights
spring.datasource.username=musicrights_user
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.globally_quoted_identifiers=true